### ISSUE TITLE
Reloading All QoS rules - don't drop packets for customers when reloading

### ISSUE THREAD

**Issue by interduo** [rchac/LibreQoS#47] opened 2022-08-29 14:48 UTC
> It rips and replaces all classes at each run. For ~500 hosts thats usually just a few seconds. this is done because it gets very convoluted to track class ids when changing them on the fly.

0 Packet lost when commiting changes ?

> I tested right now. On a network of 350 subs, I saw just 1 single packet lost during the refresh. I tested at an interval of 100ms. So not enough packet loss to cause perceptible issues on most networks.

Single packet lost per customer means many packets lost for the wole router :-)

In our Linux router we now we use `tc batch` means:

```
  -b, -b filename, -batch, -batch filename
              read commands from provided file or standard input and
              invoke them.  First failure will cause termination of tc.
```

We generate rules to files and then just load the file like
```
/sbin/tc -f -b /etc/router/qos/hfsc/down_class_current
/sbin/tc -f -b /etc/router/qos/hfsc/down_qdisc_current
/sbin/tc -f -b /etc/router/qos/hfsc/down_filter_nets_current
/sbin/tc -f -b /etc/router/qos/hfsc/down_filter_current
```
This is much more efficient. This is also useful as a startup rules for VM.

Maybe this performance change could be also implemented in LibreQoS?

**Comment by interduo** [comment] 2022-09-07 14:39
I write an integration between my CRM and LibreQoS.

```
# wc -l ShapedDevices.csv
3166 ShapedDevices.csv
```

Whole reload takes about 30-35 seconds.

My suggested for main optimalisation:
- generate commands in temporary file and then run those commands,
- make default queue at first,

**Comment by rchac** [comment] 2022-09-07 14:43
I wonder if it's the print commands slowing it down. Yeah let's try just adding them to a command list and then execute after printing the qdisc layout to see if that speeds it up.

**Comment by interduo** [comment] 2022-09-07 15:03
maybe all the print commands should be only with --debug ?

**Comment by interduo** [comment] 2022-09-07 15:04
> I wonder if it's the print commands slowing it down. Yeah let's try just adding them to a command list and then execute after printing the qdisc layout to see if that speeds it up.

I checked that: removing the lines with print dont help even a one single second

**Comment by interduo** [comment] 2022-09-07 15:06
> I wonder if it's the print commands slowing it down. Yeah let's try just adding them to a command list and then execute after printing the qdisc layout to see if that speeds it up.

HTB classes commands should be groupped and insert with a --batch like I mentioned here earlier.
I've got the same problem on my qos scripts writen from scratch.

**Comment by rchac** [comment] 2022-09-07 15:11
That makes sense. So tc batch accepts a text file with all the tc commands listed. No json needed?

**Comment by interduo** [comment] 2022-09-07 15:12
Yes :)

**Comment by interduo** [comment] 2022-09-07 15:14
If You do this I will test again on the same files and check running time.

**Comment by rchac** [comment] 2022-09-07 15:25
Let's see if this works https://github.com/rchac/LibreQoS/commit/f5618fdb9bf9a4f018c73cd0fff509dd418f70bd

**Comment by interduo** [comment] 2022-09-07 15:31
7 seconds instead of 31... Nice :)

**Comment by rchac** [comment] 2022-09-07 15:33
Nice! The remaining is probably due to the many individual commands of xdp-cpumap-tc. I'll check if there's any batch option or similar.

**Comment by rchac** [comment] 2022-09-07 15:42
Probably not an option yet. ![image](https://user-images.githubusercontent.com/22501920/188920643-3c3c74bd-8767-4aab-ba29-f363f2512da4.png)

However, if we implement the [xdp toggle option I'm considering](https://github.com/rchac/LibreQoS/issues/11#issuecomment-1237591488), that would allow us to shave off a few more of those seconds for non-XDP users.

**Comment by interduo** [comment] 2022-09-07 16:03
> Probably not an option yet. ![image](https://user-images.githubusercontent.com/22501920/188920643-3c3c74bd-8767-4aab-ba29-f363f2512da4.png)
> 
> However, if we implement the [xdp toggle option I'm considering](https://github.com/rchac/LibreQoS/issues/11#issuecomment-1237591488), that would allow us to shave off a few more of those seconds for non-XDP users.

I dont understand where You see the time savings...

**Comment by interduo** [comment] 2022-09-07 16:16
For me the most thing is no packet lost during the reloading. If we use batch Mode there would be no packet lost I think.

Did You Save all needed cmds in some startupfile?

**Comment by interduo** [comment] 2022-09-07 16:47
@rchac what is the time in place where You are? Greetings from Poland from Lubartów!

**Comment by rchac** [comment] 2022-09-07 17:30
@interduo Located in West Texas, Mountain Time Zone. Greetings from El Paso! 🌵

And currently, the IP filtering is all handled by XDP_redirect, so those are added one-by-one as console commands, even though we made the TC queue setup a batch operation. If we make an XDP on/off toggle, it would be viable to reload the rules with a batch file for both queues AND IP filters, but at the cost of losing multple CPU core support. For some it may be a helpful tradeoff, I'm not sure.

**Comment by interduo** [comment] 2022-09-07 17:35
I think we should invest time only in performant solutions - that is the main reason people come here. 

"I don't like work arounds. Like systems that works."

**Comment by rchac** [comment] 2022-09-07 17:39
Fair enough. Plus it would get messy to manage the dual approach over time. Agreed. 👍 If you know any developers familiar with C, we are hoping to raise funds to get someone to add features to xdp-cpumap-tc, such as [IPv6](https://github.com/xdp-project/xdp-cpumap-tc/issues/4). Batch filter updates would be great too to reduce reload time substantially.

**Comment by interduo** [comment] 2022-09-07 17:45
I am PHP programmer with good skills at SysOp/Networking/VM/Storage.

If it would be PHP project I would send PRs - if its Python i can only make issues with resolve and proppose an architecture of 'app', testing and debugging or the things but not Python now.

**Comment by interduo** [comment] 2022-09-08 19:38
Reloading peformance...what about BPF
https://man7.org/linux/man-pages/man8/tc-bpf.8.html could it be used for uploading the rules for classify in one file?

**Comment by rchac** [comment] 2022-09-08 19:59
We may need to suggest a patch to [xdp_iphash_to_cpu_cmdline.c](https://github.com/xdp-project/xdp-cpumap-tc/blob/24e3e5b3e71c43453485a8371a9c97f5bc6c4bbe/src/xdp_iphash_to_cpu_cmdline.c) to allow for multiple IPs (text input file?) in one batch command. I believe the project's developer is quite busy but maybe we can find a way to modify the existing code to achieve that.

**Comment by interduo** [comment] 2022-09-08 20:29
If You write an issue there - please get a link here.

**Comment by rchac** [comment] 2022-09-08 21:17
Before I reach out to them, I just want to be sure we correctly identify the cause of packet loss on reload.
Could you please try this command to see if you get packet loss?
```
sudo tc qdisc delete dev ens1 root
sudo tc qdisc delete dev ens2 root
```
where ens1 and ens2 are your interfaces.

**Comment by rchac** [comment] 2022-09-08 21:25
Fair enough. I will try it too early tomorrow morning when clients are asleep to see if I can figure it out as well.

**Comment by interduo** [comment] 2022-09-09 06:30
I my tests deleting root queues 
```
sudo tc qdisc delete dev ens1 root
sudo tc qdisc delete dev ens2 root
```
do not do packetlosts

**Comment by interduo** [comment] 2022-09-09 08:58
@rchac what about that: https://github.com/rchac/LibreQoS/issues/47#issuecomment-1241151422 ?

**Comment by rchac** [comment] 2022-09-09 09:04
> do not do packetlosts

Thats good to hear. Then these changes I just made may help.
I reworked it to where if it's the first time LibreQoS has run since boot, it will set up xdp from scratch like normal (triggering minor packet loss). However, if it is NOT the first time LibreQoS has run since boot (second run, third run), it will just "clear" and re-add IP filters for xdp. Ideally, this should prevent packet loss on every run after the first run.

Could you try it and let me know if it helps? https://github.com/rchac/LibreQoS/commit/360c0a0485df99a47934c7d5ebf40685a6246d08

**Comment by rchac** [comment] 2022-09-09 09:10
> @rchac what about that: [#47 (comment)](https://github.com/rchac/LibreQoS/issues/47#issuecomment-1241151422) ?

That does not appear to be the issue or cause of the packet loss. If it was, the packet loss would last 8 continuous seconds each time you run it. It's usually way less than that from what I understand. I think the minor packet loss is caused by the XDP program being reloaded onto the NIC or virtual NIC. This change, hopefully, should work around that https://github.com/rchac/LibreQoS/commit/360c0a0485df99a47934c7d5ebf40685a6246d08

**Comment by interduo** [comment] 2022-09-09 09:21
1. We need now to install `pip install psutil` it should be added to manual.
2.
```
Traceback (most recent call last):
  File "/root/LibreQoS2/v1.2/LibreQoS.py", line 527, in <module>
    refreshShapers()
  File "/root/LibreQoS2/v1.2/LibreQoS.py", line 437, in refreshShapers
    shell('./xdp-cpumap-tc/src/xdp_iphash_to_cpu --dev ' + interfaceA + ' --lan')
  File "/root/LibreQoS2/v1.2/LibreQoS.py", line 30, in shell
    logging.info(result)
NameError: name 'result' is not defined
```

**Comment by rchac** [comment] 2022-09-09 09:22
https://github.com/rchac/LibreQoS/commit/643bcba584194e75fc5dd3e26288ce5a2e8ea526

**Comment by interduo** [comment] 2022-09-09 11:01
I've catched something like that:

part of log:
```
key: 0x20513AC
Error: Exclusivity flag on, cannot modify.
RTNETLINK answers: File exists
RTNETLINK answers: Invalid argument
RTNETLINK answers: File exists
Error: Exclusivity flag on, cannot modify.
Error: Exclusivity flag on, cannot modify.
RTNETLINK answers: File exists
RTNETLINK answers: Invalid argument
RTNETLINK answers: File exists
Error: Exclusivity flag on, cannot modify.
Error: Exclusivity flag on, cannot modify.
```

**Comment by interduo** [comment] 2022-09-09 11:04
After reboot it happen only when I try to load LibreQoS.py second time.

**Comment by rchac** [comment] 2022-09-09 13:22
Can I see full console output please? Attempted fix https://github.com/rchac/LibreQoS/commit/d958cc0edef0ba84acd135365f594874dd37eb24

**Comment by interduo** [comment] 2022-09-09 13:31
@rchac http://kłopotek.pl/libre_startuplog2.txt

**Comment by rchac** [comment] 2022-09-09 13:33
Gotcha. Thank you. Should now be fixed with https://github.com/rchac/LibreQoS/commit/d958cc0edef0ba84acd135365f594874dd37eb24

**Comment by interduo** [comment] 2022-09-09 13:37
When i run startup:
```
Error: Class doesn't support blocks.
We have an error talking to the kernel
Error: Specified class doesn't exist.
We have an error talking to the kernel
Error: Failed to find qdisc with specified handle.
Error: Class doesn't support blocks.
We have an error talking to the kernel
Error: Specified class doesn't exist.
We have an error talking to the kernel
Error: Failed to find qdisc with specified handle.
```
Maybe we should put this in `linux-tc.txt` and use -f parameter?

**Comment by rchac** [comment] 2022-09-09 13:40
Although those errors are benign - here's a possible remedy patch to the confusing false "errors" https://github.com/rchac/LibreQoS/commit/0431625caebfdd114b93475c2f3d0c338eaa2599

**Comment by rchac** [comment] 2022-09-09 13:48
Hopefully this version should reduce the dropped packet period on reload from the current 50ms per subscriber to <25ms per subscriber.

**Comment by interduo** [comment] 2022-09-11 14:01
I can't catch where the drops come from but - maybe when dropping tc queues firstly we need to stop the filters first then empty packet buffer and then lastly remove the classes? Maybe the drops come from that we drop classes with packets inside token bucket buffer?

The next thing is we should add default classes just after we create tc class. If I understanded generated linux_tc.txt correctly - now we add then at the end.
python3
So we've got 2 situations:
- drops when we do `systemctl LibreQoS stop`,
- drops when we do `python3 LibreQoS.py`

**Comment by rchac** [comment] 2022-09-11 17:25
> The next thing is we should add default classes just after we create tc class. If I understanded generated linux_tc.txt correctly - now we add then at the end.

It actually creates them immediately. The other commands are "generated" (not yet run) first and stored, so that they can be quickly executed with linux tc batch right afterword.

> Did You checked xdp-loader? Maybe we could use it for loading filters?

xdp-loader loads xdp programs (such as xdp-cpumap-tc, which we use for ip redirect into CPU cores). It cannot redirect IP traffic to CPU cores by itself.

> maybe when dropping tc queues firstly we need to stop the filters first then empty packet buffer and then lastly remove the classes? Maybe the drops come from that we drop classes with packets inside token bucket buffer?

Change made to see if it improves it. https://github.com/rchac/LibreQoS/commit/ada20de23b7d7d967bde88a84cfce5a86b123b1a
We now clear IP filters before removing xdp filters and qdiscs from the interface. This should reduce drops.

Also please ensure your LibreQoS.service is as follows:
```
[Unit]
After=network.service

[Service]
WorkingDirectory=/home/YOUR_USERNAME/LibreQoS/v1.2
ExecStart=/usr/bin/python3 /home/YOUR_USERNAME/LibreQoS/v1.2/scheduled.py
ExecStopPost=/bin/bash -c '/usr/bin/python3 /home/YOUR_USERNAME/LibreQoS/v1.2/LibreQoS.py --clearrules'
ExecStop=/bin/bash -c '/usr/bin/python3 /home/YOUR_USERNAME/LibreQoS/v1.2/LibreQoS.py --clearrules'
Restart=always

[Install]
WantedBy=default.target
```

How long is the drop lasting in milliseconds?

**Comment by interduo** [comment] 2022-09-13 16:25
When I run ping with interval 1s every time it drops one or two packets.

**Comment by interduo** [comment] 2022-09-13 16:43
When You do reloading almost all cores goes to 100% use for the time of reloading.
Maybe this generates losses ?

**Comment by rchac** [comment] 2022-09-13 21:49
> When You do reloading almost all cores goes to 100% use for the time of reloading. Maybe this generates losses ?

That would explain it. I bet for the brief time XDP IP filters are reloading, that traffic takes a slower CPU-bound path (maybe single qdisc locked?) through the kernel, and it chokes up your CPU.

What does htop look like when you're running under regular load?

**Comment by rchac** [comment] 2022-09-13 22:16
Maybe if instead of deleting the qdisc when clearing the rules (which defaults to a single CPU fq_codel qdisc), we should replace with an MQ each time?

**Comment by interduo** [comment] 2022-09-13 22:20
We could try.

**Comment by interduo** [comment] 2022-09-14 07:33
Write me on my whats (+48607893111) up. I could give You anydesk with SSH. It will be better than recording videos.

**Comment by interduo** [comment] 2022-09-14 12:15
This issue is hard to eliminate but we could limit the need of doing full reloading to minimum by:
https://github.com/rchac/LibreQoS/issues/49

**Comment by rchac** [comment] 2022-10-20 21:30
Feature added in v1.3-alpha.

**Closed by rchac** 2022-10-20 21:30 UTC
